# NumPy Fundamentals: Manipulating Matrices
Please follow the instructions and uncomment the skeleton code as necessary.

This assignment is due in addition to the small group assignment before the next class

In [87]:
import numpy as np

In [10]:
# Create a 3x3x3 np.array
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
print(my_array)


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


## Multidimensional Indexing

### Q.1 Print the value `2.0` from `my_array` using its index

In [12]:
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
print((my_array)[1,0,0])

2.0


#### Q.2 Use multidimensional slicing to print a 3x3 array that contains *all* values of `2` from `my_array`.

In [13]:
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
print((my_array)[1])

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


#### Q.3 Use multidimensional slicing to add `5` to every other element in `my_array` such that `print(new_array)` outputs

```python
[[[6. 1. 6.]
  [1. 6. 1.]
  [6. 1. 6.]]

 [[7. 2. 7.]
  [2. 7. 2.]
  [7. 2. 7.]]

 [[8. 3. 8.]
  [3. 8. 3.]
  [8. 3. 8.]]]
```

In [85]:
# create a copy of my_array named new_array
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
new_array = my_array

# add 5 to every other element
# first colon --> start at index x
# second colon --> stop before index y
# third colon --> skip z elements
# each comma --> more specific
new_array[0:3, 0:3:2, 0:3:2] += 5         # add 5 to the corner elements
new_array[0:3, 1:2:2, 1:2:2] += 5         # add 5 to the center elements
print(new_array)


[[[6. 1. 6.]
  [1. 6. 1.]
  [6. 1. 6.]]

 [[7. 2. 7.]
  [2. 7. 2.]
  [7. 2. 7.]]

 [[8. 3. 8.]
  [3. 8. 3.]
  [8. 3. 8.]]]


## Reshaping Matrices

#### Please refer to your notes on the `transpose`, `reshape`, and `flatten` methods to answer questions 4-6. 

#### Q.4 Create a 1D array from on `my_array`.

In [112]:
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
my_1d_array = my_array.flatten()
print(my_1d_array)

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
b = a.reshape(4, 4)
c = a.reshape(2, 2, 4)
d = a.reshape(2, 2, 2, 2)
print(d[0,1,0,1])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3.
 3. 3. 3.]
5


#### Q.5 Create a 2D array from `my_array` that has 3 rows and 9 columns

In [93]:
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
my_2d_array = my_array.reshape(3,9)
print(my_2d_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]]


#### Q.6 Create a new 3D array from `my_array` so that each 3x3 sub-array has at least one row with the values `[1, 2, 3]`.

In [94]:
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
transposed_array = my_array.transpose()
print(transposed_array)

[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]
